In [6]:
## Getting Started

In [3]:
## Install tensor flow as explained over https://www.tensorflow.org/install/install_windows

In [4]:
import tensorflow as tf

In [5]:
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

b'Hello, TensorFlow!'


In [7]:
## b stants for bytes -- interesting how it wants to give us that information!

In [14]:
a = tf.constant([5])
b = tf.constant(3)
c = tf.add(a,b)

In [12]:
print(c)

Tensor("Add_1:0", shape=(1,), dtype=int32)


In [15]:
sess.run(c)

array([8])

In [20]:
## counter and loops

In [16]:
state = tf.Variable(0)

In [17]:
one = tf.constant(1)
nv = tf.add(state,one)
update = tf.assign(state,nv)

In [18]:
init_op = tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [19]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(state))
    for _ in range(3):
        session.run(update)
        print(session.run(state))

0
1
2
3


In [22]:
## Placeholders

In [41]:
x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[ 2.  4.  6.]


In [48]:
## with multidim arrays

In [47]:
x = tf.placeholder("float", [None, 3])
y = x * 2

with tf.Session() as session:
    x_data = [[1, 2, 3],
              [4, 5, 6],]
    result = session.run(y, feed_dict={x: x_data})
    print(result)

[[  2.   4.   6.]
 [  8.  10.  12.]]
